### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'out/threedfront_objfeat_vqvae/objfeat_bounds.pkl'

### ISSUE THREAD

**Issue by foojayyy** [chenguolin/InstructScene#1]
I am encountering a FileNotFoundError when trying to train the Sg2Sc objfeat model. The error message is:
FileNotFoundError: [Errno 2] No such file or directory: 'out/threedfront_objfeat_vqvae/objfeat_bounds.pkl'
The error occurs at line 179 of train_sg2sc.py when the script tries to open the objfeat_bounds.pkl file with the following command:
with open(f"{args.output_dir}/{args.fvqvae_tag}/objfeat_bounds.pkl", "rb") as f:
I have confirmed that the out directory and the threedfront_objfeat_vqvae subdirectory exist, but the objfeat_bounds.pkl file is missing.
I would appreciate any guidance on how to resolve this issue. I have tried to debug it myself, but I am stuck and need further assistance. Thank you for your help.

**Comment by chenguolin** [comment]
Hi @foojayyy,

The `objfeat_bounds.pkl` file is produced in the beginning of training fVQ-VAE:
https://github.com/chenguolin/InstructScene/blob/1086b15d7e783f7347ca356e43df58e6dbb092e9/src/train_objfeatvqvae.py#L202

I have uploaded this file to Huggingface and updated README.md, you can download it by:
```python
import os
from huggingface_hub import hf_hub_url
# os.system("mkdir -p out/threedfront_objfeat_vqvae/checkpoints")
# url = hf_hub_url(repo_id="chenguolin/InstructScene_dataset", filename="threedfront_objfeat_vqvae_epoch_01999.pth", repo_type="dataset")
# os.system(f"wget {url} -O out/threedfront_objfeat_vqvae/checkpoints/epoch_01999.pth")
url = hf_hub_url(repo_id="chenguolin/InstructScene_dataset", filename="objfeat_bounds.pkl", repo_type="dataset")
os.system(f"wget {url} -O out/threedfront_objfeat_vqvae/objfeat_bounds.pkl")
```

You can also prepare it by running `train_objfeatvqvae.py`.

Thank you for pointing it out!

**Comment by foojayyy** [comment]
Thank you for your guidance and sharing, I have downloaded the required file according to your instructions!
