### ISSUE TITLE
Incorporating Floor Plans into Scene Generation Based on Natural Language and Room Types

### ISSUE THREAD

**Issue by foojayyy** [chenguolin/InstructScene#11]
I noticed that the indoor scenes in this project are generated based on natural language descriptions and room types. However, it seems that generating scenes from floor plans is not covered. Do you have any thoughts or ideas on incorporating floor plans into the scene generation process?Thank you！！

**Comment by chenguolin** [comment]
Simply adding a cross-attention module with floorplan images as keys and values might be good enough.

Feel free to re-open this issue if you have further questions. :)
