### ISSUE TITLE
how to extract openshape features

### ISSUE THREAD

**Issue by PanYQQQ** [chenguolin/InstructScene#12]
I would like to ask you about the method of extracting point cloud features in openshape(openshape_pointbert_vitg14.npy). My own data and the furniture dataset of 3D-FUTURE only contain [x, y, z] information in the. obj data. However, I noticed that the openshape feature extraction method you used: https://github.com/Colin97/OpenShape_code , uses a 6-dimensional input: [x, y, z, r, g, b] as the input for the openshape model. I would like to ask, how did you handle the. obj data in the furniture dataset of 3D-FUTURE, which does not have color information, so that it can be input into the openshape model. Thank you. Looking forward to your answer!

**Comment by chenguolin** [comment]
You can use Blender to render RGB and depth images to extract colored point clouds from 3D models like `point-e` and `shap-e` did. For 3D-FUTURE OpenShape embeddings, they provide the preprocessed feature embeddings (`3D-FUTURE.tar.gz`) in HuggingFace [here](https://huggingface.co/datasets/OpenShape/openshape-training-data/tree/main). We directly used the provided feature embeddings.
