### ISSUE TITLE
SAVE SCENE MODEL 

### ISSUE THREAD

**Issue by foojayyy** [chenguolin/InstructScene#5]
Is there a way to save 3D scene model files (non-image)? Thank you!

**Comment by chenguolin** [comment]
Hi @foojayyy,

Sorry for the late reply. You can export the 3D scene model files by this function:
https://github.com/chenguolin/InstructScene/blob/d6950e929de77e26e07acbe5909269bc8252f827/src/utils/visualize.py#L218

And you can just comment out this line to keep the exported 3D scene files during inference visualization:
https://github.com/chenguolin/InstructScene/blob/d6950e929de77e26e07acbe5909269bc8252f827/src/generate_sg.py#L571
