### ISSUE TITLE
 release the dataset preprocessing scripts

### ISSUE THREAD

**Issue by franklhj** [chenguolin/InstructScene#6]
Thank you for your great work! When do you plan to release the dataset preprocessing scripts. I noticed that you have a plan to release.

**Comment by chenguolin** [comment]
Hi @franklhj,

Sorry for the late reply.

It's kind of tricky to clean the codes for dataset preprocessing, as I wrote them roughly for quick implementation. If you would like to use the preprocessed dataset, you can just download our dataset from [Huggingface](https://github.com/chenguolin/InstructScene/tree/main/dataset) directly, or you can check the 3D-FRONT preprocessing scripts in [ATISS](https://github.com/nv-tlabs/ATISS), which are almost the same as what we did.

Additionally, I have uploaded the data preprocessing script that applies OpenAI ChatGPT API for caption refinement [here](https://github.com/chenguolin/InstructScene/blob/main/dataset/caption_refinement_chatgpt.py). Hope it could be helpful.
