### ISSUE TITLE
What if I typed nothing in the texts（Instructions），it seems that the model would generate it randomly.

### ISSUE THREAD

**Issue by chengfengke** [chenguolin/InstructScene#7]
What if I typed nothing in the texts（Instructions），it seems that the model would generate it randomly.

**Comment by chengfengke** [comment]
And May you give me some examples for the bedrooms' texts?

**Comment by chenguolin** [comment]
Hi @chengfengke,

Yes, you are correct that the model will generate scenes randomly if text prompts are none.

Examples of text prompts for generation can be found in the appendix of the paper or the [project website](https://chenguolin.github.io/projects/InstructScene/), such as: "Add a corner side table with a round top to the left of a black and silver pendant lamp with lights".

**Comment by chengfengke** [comment]
thanks for your answer
