### ISSUE TITLE
The pre-training model

### ISSUE THREAD

**Issue by skf-1999** [chenguolin/InstructScene#9]
Can you provide the pre-training model of spanning graph prior and layout decoder? Thank you very much！

**Comment by arjuntheprogrammer** [comment]
I have created my own checkpoints by training them on Nvidia L4 GPU.

For 2000 epochs (living room) and:
- for layout decoder it took 2 days
- for scene graph it took 4 days

Let me know what would be the best way to include the checkpoints with this repo for everyone to use.

**Comment by arjuntheprogrammer** [comment]
Hi @sunkaifan - I have created a PR on Hugging face and uploaded the checkpoints for SceneGraph and LayoutDecoder for bedroom.

Please check:
<https://huggingface.co/datasets/chenguolin/InstructScene_dataset/tree/cb526c11234b8e6ad76a49f9754e236a51b28c24>

<https://huggingface.co/datasets/chenguolin/InstructScene_dataset/tree/f658bd29303172cf84ac6fa8b625e83ded56ec3a>

![image](https://github.com/chenguolin/InstructScene/assets/15984084/82ed14a0-d4d3-47aa-bacf-a9d0682de48a)

**Comment by skf-1999** [comment]
Thank you, very good job! Will the pre-training model of living room and dining room be open source in the future?

**Comment by arjuntheprogrammer** [comment]
> Thank you, very good job! Will the pre-training model of living room and dining room be open source in the future?

If I get time, I will upload it for the living and dining room as well.

**Comment by skf-1999** [comment]
Thanks for your reply!

**Comment by chenguolin** [comment]
Hi @arjuntheprogrammer, thank you very much for sharing the pretrained parameters! :)

I've updated README to inform that the pretrained models are uploaded to HuggingFace.

**Comment by YosinLiu** [comment]
@chenguolin Hi, Can you provide the pre-training model of livingroom and diningroom? Thank you very much！

**Comment by TechieJessi** [comment]
Could you kindly provide me with the pre-trained models for the living room and dining room?
